# Generated by Django 4.2.1 on 2023-05-19 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateTimeField(blank=True, default='2100-07-23 21:27', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FIC', 'FICTION'), ('POL', 'POLITICS'), ('ROM', 'ROMANCE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Y', 'YORUBA'), ('H', 'HAUSA'), ('I', 'IGBO'), ('E', 'ENGLISH')], max_length=15),
        ),
    ]
