# Generated by Django 4.2.1 on 2023-05-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0003_remove_author_date_of_death_alter_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_death',
            field=models.DateTimeField(blank=True, default='2100-07-23 21:27', null=True),
        ),
    ]
